### ISSUE TITLE
西电生求助

### ISSUE THREAD

**Issue by poisonous771** [Pairman/Xddailyup#1]
请问需要更改代码吗，运行了报错
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1125)

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='xxcapp.xidian.edu.cn', port=443): Max retries exceeded with url: /uc/wap/login/check (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1125)')))

requests.exceptions.SSLError: HTTPSConnectionPool(host='xxcapp.xidian.edu.cn', port=443): Max retries exceeded with url: /uc/wap/login/check (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1125)')))

**Comment by Pairman** [comment]
请问使用时开了代理之类的吗？如果有，关掉试一试。

**Comment by Pairman** [comment]
试着更新你的urllib3==1.26.7
